#****************
#以UTF-8格式保存*
#****************
spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发
  application:
    name:mscloud-config-fuc-dev
---
spring:
  profiles: test #测试
  application:
    name:mscloud-config-fuc-test