#****************
#以UTF-8格式保存*
#****************
spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev #开发
  application:
    name:mscloud-config-client
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:7001/eureka
---
server:
  port: 8202
spring:
  profiles: test #测试
  application:
    name:mscloud-config-client
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:7001/eureka